import React, { createContext, useContext, useState, useCallback, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};

const translations = {
  en: {
    appName: 'Dawri',
    appSubtitle: 'University Queue Management System',
    welcome: 'Welcome',
    login: 'Login',
    signup: 'Sign Up',
    logout: 'Logout',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    studentId: 'Student ID',
    firstName: 'First Name',
    lastName: 'Last Name',
    phone: 'Phone Number',
    optional: 'Optional',
    required: 'Required',
    submit: 'Submit',
    cancel: 'Cancel',
    confirm: 'Confirm',
    delete: 'Delete',
    edit: 'Edit',
    save: 'Save',
    back: 'Back',
    next: 'Next',
    search: 'Search',
    loading: 'Loading...',
    noData: 'No data available',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    info: 'Information',
    haveAccount: 'Already have an account?',
    noAccount: "Don't have an account?",
    loginHere: 'Login here',
    signupHere: 'Sign up here',
    forgotPassword: 'Forgot Password?',
    studentLogin: 'Student Login',
    studentSignup: 'Student Registration',
    guestLogin: 'Guest Login',
    guestSignup: 'Guest Registration',
    staffLogin: 'Staff Login',
    adminLogin: 'Admin Login',
    enterStudentId: 'Enter your student ID',
    enterPassword: 'Enter your password',
    createPassword: 'Create a password',
    confirmYourPassword: 'Confirm your password',
    enterEmail: 'Enter your email',
    enterPhone: 'Enter your phone number',
    enterFirstName: 'Enter your first name',
    enterLastName: 'Enter your last name',
    enterContactValue: 'Enter your phone or email',
    selectContactMethod: 'Select contact method',
    contactMethod: 'Contact Method',
    contactValue: 'Contact Value',
    selectIssue: 'Select Issue Type',
    issueTypes: 'Issue Types',
    admission: 'Admission',
    financial: 'Financial',
    academic: 'Academic',
    itSupport: 'IT Support',
    studentAffairs: 'Student Affairs',
    other: 'Other',
    staffInfo: 'Staff Information',
    staffName: 'Staff Name',
    roomNumber: 'Room Number',
    block: 'Block',
    floor: 'Floor',
    queueStatus: 'Queue Status',
    yourPosition: 'Your Position',
    peopleBefore: 'People Before You',
    estimatedWait: 'Estimated Wait Time',
    minutes: 'minutes',
    currentQueue: 'Current Queue',
    confirmQueue: 'Confirm Queue',
    cancelQueue: 'Cancel Queue',
    queueConfirmed: 'Queue Confirmed!',
    queueCancelled: 'Queue Cancelled',
    ticketNumber: 'Ticket Number',
    yourTurn: 'Your Turn Now!',
    notifications: 'Notifications',
    noNotifications: 'No notifications',
    markAllRead: 'Mark all as read',
    guestPriority: 'Guest Priority',
    dashboard: 'Dashboard',
    myAppointments: 'My Appointments',
    activeAppointment: 'Active Appointment',
    statistics: 'Statistics',
    profile: 'Profile',
    settings: 'Settings',
    totalVisits: 'Total Visits',
    completed: 'Completed',
    averageWait: 'Average Wait Time',
    waiting: 'Waiting',
    serving: 'Serving',
    served: 'Served',
    cancelled: 'Cancelled',
    selectStaff: 'Select Staff Member',
    noStaffAvailable: 'No staff available for this issue type',
    description: 'Description',
    optionalDescription: 'Optional description of your issue',
    confirmAppointment: 'Confirm Appointment',
    cancelAppointment: 'Cancel Appointment',
    appointmentCreated: 'Appointment created successfully!',
    goToDashboard: 'Go to Dashboard',
    viewQueueStatus: 'View Queue Status',
    createNewAppointment: 'Create New Appointment',
    noActiveAppointment: 'No active appointment',
    createAppointmentPrompt: "You don't have an active appointment. Create one now?",
    appointmentHistory: 'Appointment History',
    status: 'Status',
    date: 'Date',
    staff: 'Staff',
    issueType: 'Issue Type',
    language: 'Language',
    english: 'English',
    arabic: 'Arabic',
    theme: 'Theme',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    pushNotifications: 'Push Notifications',
    about: 'About',
    version: 'Version 2.0',
    poweredBy: 'Powered by Dawri',
    invalidCredentials: 'Invalid credentials',
    passwordMismatch: 'Passwords do not match',
    emailExists: 'Email already exists',
    idExists: 'Student ID already exists',
    queueFull: 'Queue is full',
    staffUnavailable: 'Staff is unavailable',
    alreadyInQueue: 'You are already in queue',
    guestPriorityEnabled: 'Guest priority is enabled',
    selectIssueTypePrompt: 'Please select the type of issue you need help with',
    availableStaff: 'Available Staff',
    queueLength: 'Queue Length',
    avgServiceTime: 'Avg Service Time',
    location: 'Location',
    servingNow: 'Serving Now',
    waitingList: 'Waiting List',
    noPeopleInQueue: 'No people in queue',
    serveNext: 'Serve Next',
    markAsServed: 'Mark as Served',
    resolveRemotely: 'Resolve Remotely',
    enterResolutionNote: 'Enter resolution note (optional)',
    staffDashboard: 'Staff Dashboard',
    adminDashboard: 'Admin Dashboard',
    manageStaff: 'Manage Staff',
    manageIssueTypes: 'Manage Issue Types',
    analytics: 'Analytics',
    peakHours: 'Peak Hours',
    systemSettings: 'System Settings',
    addStaff: 'Add Staff',
    editStaff: 'Edit Staff',
    deleteStaffConfirm: 'Are you sure you want to delete this staff member?',
    addIssueType: 'Add Issue Type',
    editIssueType: 'Edit Issue Type',
    deleteIssueTypeConfirm: 'Are you sure you want to delete this issue type?',
    color: 'Color',
    icon: 'Icon',
    nameAr: 'Arabic Name',
    enterNameAr: 'Enter Arabic name',
    studentsServed: 'Students Served',
    guestsServed: 'Guests Served',
    totalServed: 'Total Served',
    avgWaitTime: 'Avg Wait Time',
    busiestSection: 'Busiest Section',
    busiestHour: 'Busiest Hour',
    todayStats: "Today's Statistics",
    weeklyStats: 'Weekly Statistics',
    monthlyStats: 'Monthly Statistics',
    recentActivity: 'Recent Activity',
    noRecentActivity: 'No recent activity',
    serveQueue: 'Serve Queue',
    myStats: 'My Statistics',
    availability: 'Availability',
    available: 'Available',
    unavailable: 'Unavailable',
    paused: 'Paused',
    maxQueueLimit: 'Max Queue Limit',
    school: 'School',
    enterSchool: 'Enter school name (optional)',
    schoolOptional: 'School (Optional)',
  },
  ar: {
    appName: 'دوري',
    appSubtitle: 'نظام إدارة الطابور الجامعي',
    welcome: 'مرحباً',
    login: 'تسجيل الدخول',
    signup: 'إنشاء حساب',
    logout: 'تسجيل الخروج',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    confirmPassword: 'تأكيد كلمة المرور',
    studentId: 'رقم الطالب',
    firstName: 'الاسم الأول',
    lastName: 'الاسم الأخير',
    phone: 'رقم الهاتف',
    optional: 'اختياري',
    required: 'مطلوب',
    submit: 'إرسال',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    delete: 'حذف',
    edit: 'تعديل',
    save: 'حفظ',
    back: 'رجوع',
    next: 'التالي',
    search: 'بحث',
    loading: 'جاري التحميل...',
    noData: 'لا توجد بيانات',
    error: 'خطأ',
    success: 'نجاح',
    warning: 'تحذير',
    info: 'معلومات',
    haveAccount: 'لديك حساب بالفعل؟',
    noAccount: 'ليس لديك حساب؟',
    loginHere: 'سجل الدخول هنا',
    signupHere: 'سجل هنا',
    forgotPassword: 'نسيت كلمة المرور؟',
    studentLogin: 'تسجيل دخول الطالب',
    studentSignup: 'تسجيل الطالب',
    guestLogin: 'تسجيل دخول الضيف',
    guestSignup: 'تسجيل الضيف',
    staffLogin: 'تسجيل دخول الموظف',
    adminLogin: 'تسجيل دخول المشرف',
    enterStudentId: 'أدخل رقم الطالب',
    enterPassword: 'أدخل كلمة المرور',
    createPassword: 'أنشئ كلمة مرور',
    confirmYourPassword: 'أكد كلمة المرور',
    enterEmail: 'أدخل بريدك الإلكتروني',
    enterPhone: 'أدخل رقم هاتفك',
    enterFirstName: 'أدخل اسمك الأول',
    enterLastName: 'أدخل اسمك الأخير',
    enterContactValue: 'أدخل هاتفك أو بريدك',
    selectContactMethod: 'اختر طريقة الاتصال',
    contactMethod: 'طريقة الاتصال',
    contactValue: 'قيمة الاتصال',
    selectIssue: 'اختر نوع المشكلة',
    issueTypes: 'أنواع المشاكل',
    admission: 'القبول',
    financial: 'المالية',
    academic: 'الأكاديمية',
    itSupport: 'دعم تقني',
    studentAffairs: 'شؤون الطلاب',
    other: 'أخرى',
    staffInfo: 'معلومات الموظف',
    staffName: 'اسم الموظف',
    roomNumber: 'رقم الغرفة',
    block: 'المبنى',
    floor: 'الطابق',
    queueStatus: 'حالة الطابور',
    yourPosition: 'موقعك',
    peopleBefore: 'الأشخاص قبلك',
    estimatedWait: 'وقت الانتظار المتوقع',
    minutes: 'دقيقة',
    currentQueue: 'الطابور الحالي',
    confirmQueue: 'تأكيد الطابور',
    cancelQueue: 'إلغاء الطابور',
    queueConfirmed: 'تم تأكيد الطابور!',
    queueCancelled: 'تم إلغاء الطابور',
    ticketNumber: 'رقم التذكرة',
    yourTurn: 'دورك الآن!',
    notifications: 'الإشعارات',
    noNotifications: 'لا توجد إشعارات',
    markAllRead: 'تحديد الكل كمقروء',
    guestPriority: 'أولوية الضيوف',
    dashboard: 'لوحة التحكم',
    myAppointments: 'مواعيدي',
    activeAppointment: 'الموعد النشط',
    statistics: 'الإحصائيات',
    profile: 'الملف الشخصي',
    settings: 'الإعدادات',
    totalVisits: 'إجمالي الزيارات',
    completed: 'مكتمل',
    averageWait: 'متوسط وقت الانتظار',
    waiting: 'في الانتظار',
    serving: 'جاري الخدمة',
    served: 'تمت الخدمة',
    cancelled: 'ملغى',
    selectStaff: 'اختر موظف',
    noStaffAvailable: 'لا يوجد موظفون متاحون',
    description: 'الوصف',
    optionalDescription: 'وصف اختياري لمشكلتك',
    confirmAppointment: 'تأكيد الموعد',
    cancelAppointment: 'إلغاء الموعد',
    appointmentCreated: 'تم إنشاء الموعد بنجاح!',
    goToDashboard: 'الذهاب للوحة التحكم',
    viewQueueStatus: 'عرض حالة الطابور',
    createNewAppointment: 'إنشاء موعد جديد',
    noActiveAppointment: 'لا يوجد موعد نشط',
    createAppointmentPrompt: 'ليس لديك موعد نشط. إنشاء واحد الآن؟',
    appointmentHistory: 'سجل المواعيد',
    status: 'الحالة',
    date: 'التاريخ',
    staff: 'الموظف',
    issueType: 'نوع المشكلة',
    language: 'اللغة',
    english: 'English',
    arabic: 'العربية',
    theme: 'المظهر',
    darkMode: 'الوضع الداكن',
    lightMode: 'الوضع الفاتح',
    pushNotifications: 'الإشعارات الفورية',
    about: 'حول',
    version: 'الإصدار 2.0',
    poweredBy: 'مدعوم من دوري',
    invalidCredentials: 'بيانات غير صحيحة',
    passwordMismatch: 'كلمات المرور غير متطابقة',
    emailExists: 'البريد الإلكتروني موجود مسبقاً',
    idExists: 'رقم الطالب موجود مسبقاً',
    queueFull: 'الطابور ممتلئ',
    staffUnavailable: 'الموظف غير متاح',
    alreadyInQueue: 'أنت في الطابور بالفعل',
    guestPriorityEnabled: 'أولوية الضيف مفعلة',
    selectIssueTypePrompt: 'يرجى اختيار نوع المشكلة',
    availableStaff: 'الموظفون المتاحون',
    queueLength: 'طول الطابور',
    avgServiceTime: 'متوسط وقت الخدمة',
    location: 'الموقع',
    servingNow: 'يخدم الآن',
    waitingList: 'قائمة الانتظار',
    noPeopleInQueue: 'لا يوجد أشخاص في الطابور',
    serveNext: 'خدمة التالي',
    markAsServed: 'تحديد كمخدم',
    resolveRemotely: 'حل عن بعد',
    enterResolutionNote: 'ملاحظة الحل (اختياري)',
    staffDashboard: 'لوحة تحكم الموظف',
    adminDashboard: 'لوحة تحكم المشرف',
    manageStaff: 'إدارة الموظفين',
    manageIssueTypes: 'إدارة أنواع المشاكل',
    analytics: 'التحليلات',
    peakHours: 'ساعات الذروة',
    systemSettings: 'إعدادات النظام',
    addStaff: 'إضافة موظف',
    editStaff: 'تعديل موظف',
    deleteStaffConfirm: 'هل أنت متأكد من حذف هذا الموظف؟',
    addIssueType: 'إضافة نوع مشكلة',
    editIssueType: 'تعديل نوع مشكلة',
    deleteIssueTypeConfirm: 'هل أنت متأكد من حذف هذا النوع؟',
    color: 'اللون',
    icon: 'الأيقونة',
    nameAr: 'الاسم بالعربية',
    enterNameAr: 'أدخل الاسم بالعربية',
    studentsServed: 'الطلاب المخدمون',
    guestsServed: 'الضيوف المخدمون',
    totalServed: 'إجمالي المخدمين',
    avgWaitTime: 'متوسط وقت الانتظار',
    busiestSection: 'القسم الأكثر ازدحاماً',
    busiestHour: 'ساعة الذروة',
    todayStats: 'إحصائيات اليوم',
    weeklyStats: 'إحصائيات الأسبوع',
    monthlyStats: 'إحصائيات الشهر',
    recentActivity: 'النشاط الأخير',
    noRecentActivity: 'لا يوجد نشاط حديث',
    serveQueue: 'خدمة الطابور',
    myStats: 'إحصائياتي',
    availability: 'التوفر',
    available: 'متاح',
    unavailable: 'غير متاح',
    paused: 'متوقف',
    maxQueueLimit: 'حد الطابور الأقصى',
    school: 'الكلية',
    enterSchool: 'أدخل اسم الكلية (اختياري)',
    schoolOptional: 'الكلية (اختياري)',
  },
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('en');

  useEffect(() => {
    const loadLanguage = async () => {
      try {
        const saved = await AsyncStorage.getItem('language');
        if (saved) setLang(saved);
      } catch (error) {
        console.error('Load language error:', error);
      }
    };
    loadLanguage();
  }, []);

  const t = useCallback(
    (key) => {
      return translations[lang][key] || key;
    },
    [lang]
  );

  const toggleLanguage = useCallback(async () => {
    const newLang = lang === 'en' ? 'ar' : 'en';
    setLang(newLang);
    try {
      await AsyncStorage.setItem('language', newLang);
    } catch (error) {
      console.error('Save language error:', error);
    }
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, t, toggleLanguage, isRTL: lang === 'ar' }}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;
